apiVersion: v1
kind: Service
metadata:
  name: week2-service
spec:
  ports:
  - port: 33001
    nodePort: 33001
    targetPort: http-port
    protocol: TCP
  selector:
    app: week2
  type: NodePort
