version: "3.1"

services:
  week2-mongo:
    image: bartvandenheuvel/week2-mongo:v1
    volumes:
      - "~/data:/data/db"
    networks:
     - week2
    expose:
     - "27017"

  week2-app:
    image: bartvandenheuvel/week2:v1
    networks:
     - week2
    ports:
     - "5000:5000"

networks:
    week2:
