apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
   app: testing-ability-to-run-a-pod
spec:
  containers:
  - name: love-yourself
    image: centos:7 
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo you are appriciated on $(date); sleep 10;done"]

