apiVersion: v1
kind: Pod
metadata:
  name: week2
  labels:
   app: week2-app
spec:
  containers:
  - name: week2-mongo
    image: bartvandenheuvel/week2-mongo:v1
    volumeMounts:
    - mountPath: /data
      name: mongo-volume
  - name: week2
    image: bartvandenheuvel/week2:v1.2
    ports:
    - name: week2-port
      containerPort: 5000
    env:
     - name: MONGO_DEST
       value: localhost
  volumes:
   - name: mongo-volume
     persistentVolumeClaim:
       claimName: nfs-claim1
