apiVersion: v1
kind: Pod
metadata:
  name: week2
spec:
  containers:
  - name: week2-mongo
    image: bartvandenheuvel/week2-mongo:v1
  - name: week2
    image: bartvandenheuvel/week2:v1.1
    env: 
    - name: MONGO_DEST
      value: localhost
